'use client';
import {useState,useEffect,useCallback,useRef} from 'react';
import {RefreshCw,ChevronRight,MapPin,Radio,ExternalLink,BarChart3,Info,Check,AlertCircle} from 'lucide-react';
import {Select,SelectTrigger,SelectContent,SelectItem,SelectValue} from '@/components/ui/select';
import {Progress} from '@/components/ui/progress';
import shapes from '@/data/map.json';
import {UF_NAMES,color,leader,leadershipLabel,neutralLegend,margin,integer,percent,displayName,type Result,type Results} from '@/lib/election';
const sorted=Object.entries(UF_NAMES).sort((a,b)=>a[1].localeCompare(b[1],'pt-BR'));
const callouts:Record<string,[number,number]>={RN:[712,218],PB:[724,252],PE:[714,286],AL:[699,320],SE:[678,353],ES:[641,466],RJ:[601,514],DF:[477,387]};
function Map({regions,selected,onSelect,loading}:{regions:Record<string,Result>;selected:string;onSelect:(uf:string)=>void;loading:boolean}){
 const [hover,setHover]=useState<string|null>(null);useEffect(()=>setHover(null),[selected]);const active=hover??(selected==='BR'?null:selected);const result=active?regions[active]:undefined;const first=leader(result);
 return <div className="map-canvas"><svg className="brazil" viewBox="0 0 760 730" aria-label="Mapa da apuração presidencial por estado">
 <defs><pattern id="stale-hatch" width="7" height="7" patternUnits="userSpaceOnUse" patternTransform="rotate(35)"><line y2="7" stroke="#fff" strokeOpacity=".18" strokeWidth="2"/></pattern></defs>
 {shapes.map(s=>{const r=regions[s.uf],l=leader(r);const fill=l?color(l.number):'#34414e';const opacity=l?.number?0.42+Math.min(margin(r),35)/35*.58:1;return <g key={s.uf}><path d={s.d} fill={fill} fillOpacity={opacity} className={`state ${selected===s.uf?'selected':''}`} tabIndex={0} role="button" aria-label={`${s.name}: ${l?displayName(l.name)+' lidera; '+percent(r.counted)+'% apurado':leadershipLabel(r,loading)}. Ver detalhes.`} aria-pressed={selected===s.uf} onClick={()=>onSelect(s.uf)} onKeyDown={e=>{if(e.key==='Enter'||e.key===' '){e.preventDefault();onSelect(s.uf)}}} onMouseEnter={()=>setHover(s.uf)} onMouseLeave={()=>setHover(null)} onFocus={()=>setHover(s.uf)} onBlur={()=>setHover(null)}><title>{s.name}{r?` · ${percent(r.counted)}% apurado`:''}</title></path>{r?.stale&&<path d={s.d} fill="url(#stale-hatch)" className="hatch"/>}</g>})}
 {shapes.map(s=>{const target=callouts[s.uf]??s.center;return <g key={s.uf} className="map-label" onClick={()=>onSelect(s.uf)} aria-hidden="true">{callouts[s.uf]&&<path d={`M${s.center.join(',')}L${target[0]-14},${target[1]-4}`} className="label-line"/>}<text x={target[0]} y={target[1]} textAnchor="middle">{s.uf}</text></g>})}
 <text x="490" y="637" className="ocean">O C E A N O</text><text x="490" y="661" className="ocean">A T L Â N T I C O</text>
 </svg><div className={`map-tooltip ${active?'visible':''}`} aria-hidden="true"><strong>{active?UF_NAMES[active]:''}</strong><span>{first?`${displayName(first.name)} · ${percent(first.percent)}%`:leadershipLabel(result,loading)}</span>{result&&<small>{percent(result.counted)}% apurado{result.stale?' · última leitura disponível':''}</small>}</div></div>
}
function Ranking({result,loading}:{result?:Result;loading:boolean}){return <div className="ranking">{result?result.candidates.map((c,i)=><div className="candidate" key={c.number}><div className="candidate-top"><span className="candidate-number" style={{color:color(c.number),background:`${color(c.number)}17`}}>{c.number}</span><div className="candidate-name"><strong>{displayName(c.name)}</strong><small>{c.party}{c.elected?' · Eleito':''}</small></div><div className="candidate-percent"><strong>{percent(c.percent)}<span>%</span></strong><small>{integer(c.votes)} votos</small></div></div><div className="vote-track"><div style={{width:`${Math.min(100,c.percent)}%`,background:color(c.number)}}/></div>{i===0&&result.candidates[0].votes>0&&<span className="leader-note">{leader(result)?'Na liderança':'Empate em votos'}</span>}</div>):<p className="empty">{loading?'Consultando os resultados oficiais…':'Não foi possível carregar os resultados. Tente atualizar.'}</p>}</div>}
export default function Home(){
 const [data,setData]=useState<Results|null>(null),[selected,setSelected]=useState('BR'),[busy,setBusy]=useState(true),[error,setError]=useState(false),[now,setNow]=useState(Date.now());
 const inFlight=useRef(false);const abort=useRef<AbortController|null>(null);
 const refresh=useCallback(async()=>{if(inFlight.current)return;inFlight.current=true;setBusy(true);const controller=new AbortController();abort.current=controller;const timeout=setTimeout(()=>controller.abort(),50000);try{const r=await fetch('/api/results',{signal:controller.signal});if(!r.ok)throw new Error();const body:Results=await r.json();if(!body.regions)throw new Error();setData(previous=>{if(!previous)return body;const regions={...previous.regions,...body.regions};for(const [uf,old]of Object.entries(previous.regions)){if(!body.regions[uf]||old.timestamp>body.regions[uf].timestamp)regions[uf]={...old,stale:true};}return {...body,regions}});setError(false);}catch{if(!controller.signal.aborted||document.visibilityState!=='hidden')setError(true);}finally{clearTimeout(timeout);inFlight.current=false;setBusy(false);}},[]);
 useEffect(()=>{void refresh();const timer=setInterval(()=>{setNow(Date.now());if(document.visibilityState==='visible')void refresh()},30000);const resume=()=>{if(document.visibilityState==='visible')void refresh()};document.addEventListener('visibilitychange',resume);return()=>{clearInterval(timer);document.removeEventListener('visibilitychange',resume);abort.current?.abort()}},[refresh]);
 const regions=data?.regions??{},national=regions.BR,current=regions[selected];const unavailable=data?.unavailable??[];const isStale=error||current?.stale;const old=!!current&&now-current.timestamp>10*60*1000;const name=selected==='BR'?'Brasil':UF_NAMES[selected];const candidates=Array.from(new globalThis.Map(Object.values(regions).flatMap(r=>r.candidates).map(c=>[c.number,c])).values()).sort((a,b)=>Number(a.number)-Number(b.number));const neutral=neutralLegend(regions);
 return <main><header className="header"><a className="brand" href="/" aria-label="Apuração Brasil, início"><span className="brand-icon"><BarChart3 size={23}/></span><span>apuração<span className="brand-light">brasil</span></span></a><div className="edition">ELEIÇÕES <b>2026</b></div><a className="source-link" href="https://resultados.tse.jus.br/" target="_blank" rel="noreferrer">Fonte: TSE <ExternalLink size={14}/></a></header>
 <div className="page-heading"><div><div className="eyebrow">4 DE OUTUBRO · 1º TURNO</div><h1>O voto, estado por estado.</h1><p>Apuração para presidente da República</p></div><div className="live-box"><span className={`status ${error||unavailable.length?'warning':''}`}><i/>{busy?'Atualizando':error?'Conexão interrompida':unavailable.length?'Atualização parcial':data?'Acompanhando apuração':'Conectando ao TSE'}</span><small>Consulta automática a cada 30 s</small></div></div>
 <section className="national-strip" aria-label="Resumo nacional"><div className="national-progress"><span className="metric-label">SEÇÕES APURADAS · BRASIL</span><div className="large-number">{national?percent(national.counted):'—'}<span>%</span></div><Progress value={national?.counted??0} aria-label="Porcentagem das seções apuradas no Brasil"/><small>{national?`${integer(national.sections)} de ${integer(national.totalSections)} seções`:'Aguardando dados oficiais'}</small></div><div className="national-stat"><span className="metric-label">VOTOS VÁLIDOS</span><strong>{national?integer(national.valid):'—'}</strong><small>Total nacional contabilizado</small></div><div className="national-stat"><span className="metric-label">DIFERENÇA ENTRE OS DOIS PRIMEIROS</span><strong>{national?integer((national.candidates[0]?.votes??0)-(national.candidates[1]?.votes??0)):'—'}<span> votos</span></strong><small>{national?`${percent(margin(national))} pontos percentuais`:'Aguardando apuração'}</small></div></section>
 {(error||unavailable.length>0)&&<div role="status" className="notice"><AlertCircle size={17}/><span>{error?'Não foi possível atualizar agora. Os dados anteriores foram mantidos.':`Sem atualização em ${unavailable.join(', ')}. Exibindo a última leitura disponível nessas regiões.`}</span></div>}
 <div className="workspace"><section className="map-panel"><div className="panel-heading"><div><span className="eyebrow">PANORAMA NACIONAL</span><h2>Quem lidera em cada estado</h2></div><span className="map-hint"><MapPin size={14}/> Toque para explorar</span></div><Map regions={regions} selected={selected} onSelect={setSelected} loading={busy&&!data}/><div className="map-key"><div className="scale"><span>Disputa apertada</span><div className="scale-blocks">{[.42,.57,.72,.86,1].map(o=><i key={o} style={{opacity:o}}/>)}</div><span>Vantagem maior</span></div><div className="neutral-legend" aria-label="Legenda das UFs em cinza">{neutral["no-votes"]>0&&<span className="neutral-key"><i/> Sem votos ({neutral["no-votes"]} UF{neutral["no-votes"]!==1?"s":""})</span>}{neutral.tied>0&&<span className="neutral-key"><i/> Empate ({neutral.tied} UF{neutral.tied!==1?"s":""})</span>}{neutral.unavailable>0&&<span className="neutral-key"><i/> {busy&&!data?"Carregando":"Dados indisponíveis"} ({neutral.unavailable} UF{neutral.unavailable!==1?"s":""})</span>}</div></div><div className="candidate-legend">{candidates.filter(c=>Object.values(regions).some(r=>r.uf!=='BR'&&leader(r)?.number===c.number)).map(c=><span key={c.number}><i style={{background:color(c.number)}}/>{displayName(c.name)}</span>)}</div><p className="map-caption"><Info size={14}/> As cores indicam liderança, sem projeção de vitória. Hachuras indicam dados sem atualização.</p></section>
 <aside className="results-panel"><div className="result-heading"><span className="eyebrow">RESULTADOS</span><Select value={selected} onValueChange={setSelected}><SelectTrigger className="region-select" aria-label="Selecionar estado ou Brasil"><SelectValue/></SelectTrigger><SelectContent><SelectItem value="BR">Brasil</SelectItem>{sorted.map(([uf,n])=><SelectItem value={uf} key={uf}>{n} · {uf}</SelectItem>)}</SelectContent></Select>{selected!=='BR'&&<button className="back-national" onClick={()=>setSelected('BR')}>Ver total do Brasil <ChevronRight size={13}/></button>}</div><div className="region-progress"><div><span>{current?`${percent(current.counted)}% apurado`:'Aguardando dados'}</span>{current?.counted===100?<Check size={15}/>:<Radio size={15}/>}</div><Progress value={current?.counted??0} aria-label={`Apuração em ${name}`}/></div>{current&&<div className={`timestamp ${isStale||old?'stale':''}`}>{isStale?'Última leitura disponível':old?'TSE sem nova publicação há mais de 10 min':'Publicado pelo TSE'}<span>{current.generated} · Brasília</span></div>}<Ranking result={current} loading={busy}/>{current&&<div className="other-votes"><div><span>Brancos</span><strong>{integer(current.blank)}</strong></div><div><span>Nulos</span><strong>{integer(current.nullVotes)}</strong></div><div><span>Votos contabilizados</span><strong>{integer(current.totalVotes)}</strong></div></div>}<div className="results-bottom"><button onClick={()=>void refresh()} disabled={busy} className="refresh"><RefreshCw size={15} className={busy?'spin':''}/>{busy?'Atualizando…':'Atualizar agora'}</button>{current&&<a href={current.source} target="_blank" rel="noreferrer" aria-label={`Abrir JSON do TSE para ${name}`}><ExternalLink size={16}/></a>}</div></aside></div>
 <section className="state-overview"><div className="section-title"><div><span className="eyebrow">TODAS AS UFs</span><h2>Explore a apuração</h2></div><span>26 estados e Distrito Federal</span></div><div className="state-grid">{sorted.map(([uf,n])=>{const r=regions[uf],l=leader(r);return <button key={uf} onClick={()=>{setSelected(uf);document.querySelector('.results-panel')?.scrollIntoView({behavior:'smooth',block:'start'})}} className={selected===uf?'state-tile active':'state-tile'}><span className="uf" style={{borderColor:l?color(l.number):undefined}}>{uf}</span><span className="tile-details"><strong>{n}</strong><small>{leadershipLabel(r,busy&&!data)}</small></span><span className="tile-progress">{r?`${percent(r.counted)}%`:'—'}<small>apurado{r?.stale?' · anterior':''}</small></span></button>})}</div></section>
 <footer><span><b>apuração brasil</b> · Projeto independente</span><span>Dados oficiais do TSE · Horários de Brasília · 26 estados e Distrito Federal</span><a href="https://github.com/codeforamerica/click_that_hood/blob/master/public/data/brazil-states.geojson" target="_blank" rel="noreferrer">Base cartográfica</a></footer>
 </main>
}
